# Generated by Django 2.0.3 on 2018-03-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('config_filename', models.CharField(blank=True, max_length=256, null=True)),
                ('config_text', models.TextField(blank=True, null=True)),
                ('loaded_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CruiseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField(auto_now_add=True)),
                ('cruise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('cruise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='LoggerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('config_json', models.TextField(verbose_name='configuration string')),
                ('enabled', models.BooleanField(default=True)),
                ('logger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.Logger')),
            ],
        ),
        migrations.CreateModel(
            name='LoggerConfigState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('desired', models.BooleanField(default=False)),
                ('process_id', models.IntegerField(blank=True, default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.LoggerConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('cruise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='ServerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, max_length=80, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(blank=True, max_length=80, null=True)),
                ('running', models.BooleanField(default=False)),
                ('desired', models.BooleanField(default=False)),
                ('process_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(blank=True, max_length=80, null=True)),
                ('cruise', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loggerconfig',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.Mode'),
        ),
        migrations.AddField(
            model_name='logger',
            name='current_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_config', to='gui.LoggerConfig'),
        ),
        migrations.AddField(
            model_name='logger',
            name='desired_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_config', to='gui.LoggerConfig'),
        ),
        migrations.AddField(
            model_name='cruisestate',
            name='current_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Mode'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='current_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruise_current_mode', to='gui.Mode'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='default_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruise_default_mode', to='gui.Mode'),
        ),
    ]
